accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path(r'signup/', views.signup_view, name='signup'),
    path(r'login/', views.login_view, name='login'),
    path(r'logout/', views.logout_view, name='logout'),
]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),
    url('', include('blogApp.urls')),
    url(r'^api/', include('blogApp.api.urls')),
    url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^accounts/', include('accounts.urls')),
)

blogApp/api/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

app_name = 'post_api'

router = routers.DefaultRouter()
router.register(r'post', views.PostViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

blogApp/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('', views.post_list, name='list'),
    path('post/archive', views.archive_post, name='archive'),
    path('post/<int:pk>/', views.post_detail, name='detail'),
    path('post/new/', views.post_new, name='new'),
    path('post/<int:pk>/edit', views.post_edit, name='edit'),
    path('post/search', views.search_post, name='search'),
]

accounts/models.py
from django.db import models

# Create your models here.

blogApp/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.db.models import Q


class PostManager(models.Manager):
    def posts(self):
        """Returns posts ordered by publish_date"""
        condition = Q(publish_date__lte=timezone.now()) & Q(archive_date__isnull=True)
        return self.get_queryset().filter(condition).order_by('publish_date')

    def archived_posts(self):
        """Returns archived posts ordered by archive_date"""
        return self.get_queryset().filter(archive_date__isnull=False).order_by('archive_date')

    def search_posts(self, text):
        condition = Q(text__contains=text) | Q(title__contains=text)
        return self.get_queryset().filter(condition)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    publish_date = models.DateTimeField(blank=True, null=True)
    archive_date = models.DateTimeField(blank=True, null=True)
    objects = PostManager()

    def publish(self):
        """Updates publish_date"""
        self.publish_date = timezone.now()
        self.save()

    def archive(self):
        """Updates archive_date"""
        self.archive_date = timezone.now()
        self.save()

    def is_archived(self):
        """Returns archive state"""
        return self.archive_date is not None

    def __str__(self):
        return self.title

blogApp/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'text')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET


def signup_view(request):
    """A view for unregistered users."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('post:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})


def login_view(request):
    """A view for registered users to login."""
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('post:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form': form})


@require_GET
@login_required
def logout_view(request):
    """A view for logged in users to logout."""
    logout(request)
    return redirect('post:list')

blogApp/api/views.py
from blogApp.models import Post
from rest_framework import viewsets
from .serializers import PostSerializer
from rest_framework.response import Response


class PostViewSet(viewsets.ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer

    def create(self, request):
        """Receives post request and returns saved post data."""
        serializer = PostSerializer(data=request.POST)
        serializer.is_valid()
        serializer.save(author=request.user)
        return Response(serializer.data)

blogApp/views.py
from .models import Post
from django.utils import timezone
from .forms import PostForm
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_GET


def post_list(request):
    """A list page for posts."""
    posts = Post.objects.posts()
    return render(request, 'blog/post_list.html', {'posts': posts})


def archive_post(request):
    """A list page for archived posts or archives posts."""
    if request.method == 'POST':
        pk = request.POST['pk']
        post = get_object_or_404(Post, pk=pk)
        post.archive()
    posts = Post.objects.archived_posts()
    return render(request, 'blog/post_list.html', {'posts': posts})


@login_required
def post_new(request):
    """A page for create new posts."""
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post:detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})


def post_detail(request, pk):
    """A page for post details."""
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})


@login_required
def post_edit(request, pk):
    """A page for edit posts."""
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.publish_date = timezone.now()
            post.save()
            return redirect('post:detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})


@require_GET
def search_post(request):
    text = request.GET['text']
    posts = Post.objects.search_posts(text=text)
    return render(request, 'blog/search_post_list.html', {'posts': posts})

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>login</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Login">
    </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <h1>signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Signup">
    </form>
{% endblock %}

blogApp/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <div class="post">
        {% if post.publish_date %}
            <div class="date">
                  {{ post.publish_date }}
            </div>
        {% endif %}
        {% if user.is_authenticated %}
            <form action="{% url 'post:archive' %}" method="post">
                {% csrf_token %}
                <a class="btn btn-default" href="{% url 'post:edit' pk=post.pk %}"><button type="button" class="btn btn-outline-success">{% trans "Edit" %}</button></a>
                <input type="hidden" name="pk" value="{{ post.pk }}">
                <input type="submit" class="btn btn-outline-success" value="{% trans "Archive" %}" {% if post.is_archived %} disabled {% endif %}>
            </form>

        {% endif %}
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

blogApp/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    <h2>New post</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">{% trans "Save" %}</button>
    </form>
{% endblock %}

blogApp/templates/blog/post_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.publish_date }}
            </div>
            <h1><a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

blogApp/templates/blog/search_post_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.publish_date }}
            </div>
            <h1><a href="{% url 'post:detail' pk=post.pk %}">{{ post.title }} {% if post.is_archived %} ({% trans "Archived" %}) {% endif %}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/base.html
{% load static i18n %}
<html>
<head>
    <title>Django blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01"
            aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <a class="navbar-brand" href="{% url 'post:list' %}">Django Blog</a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'post:list' %}">{% trans "Home" %} <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'post:archive' %}">{% trans "Archived Posts" %}</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'post:search' %}" method="get">
            <input class="form-control mr-sm-2" type="search" placeholder="{% trans "Search" %}" aria-label="{% trans "Search" %}" name="text">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">{% trans "Search" %}</button>
        </form>
        {% if user.is_authenticated %}
            <a href="{% url 'post:new' %}"><button type="button" class="btn btn-outline-success">{% trans "New Post" %}</button></a>
            <a href="{% url 'accounts:logout' %}"><button type="button" class="btn btn-outline-danger">{% trans "Logout" %}</button></a>
        {% else %}
            <a href="{% url 'accounts:login' %}"><button type="button" class="btn btn-outline-primary">{% trans "Login" %}</button></a>
            <a href="{% url 'accounts:signup' %}"><button type="button" class="btn btn-outline-primary">{% trans "Signup" %}</button></a>
        {% endif %}
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            {% endblock %}
        </div>
    </div>
</div>
</body>
</html>